device: 0

# # Dataset settings
feat_dim: 8189

# # Training settings
epochs: 200
optim: adam
init_lr: 0.001
weight_decay: 0.0
# use_schedule: true
use_schedule: false
step_size: 50
gamma: 0.5

lr_eval: 0.005
wd_eval: 0.0001
epochs_eval: 5000

# # Pretraining settings
# mask_ratio: 0.25  # 原先的
mask_ratio: 0.3 # 规范化一下
replace_ratio: 0.2
edge_drop: 0.3

masked_atom_loss: 1.0
masked_pe_loss: 0.1
masked_ssl_loss: 0.00001
ssl_sample: 1024
ssl_temp: 0.2
atom_recon_type: sce
alpha_l: 3.0
noise_val: 0.01

# # Encoder & Decoder setting
enc_gnn_layer: 2
embed_dim: 1024
heads: 4
gnn_dropout: 0.0
gnn_edge_dropout: 0.0
gnn_activation: elu
task_head_activation: gelu

# # Positional Encoding (PE) settings
max_freqs: 50
max_freqs2: 50
pos_activation: gelu